### ISSUE TITLE
Investigate whether to use the inferred or asserted version

### ISSUE THREAD

**Issue by cmungall** [ontodev/ncit-obo#10]
cc @mbrush

**Comment by mbrush** [comment]
Obtained the asserted vs inferred owl files from https://cbiit.nci.nih.gov/evs-download/thesaurus-downloads. They are described as follows:

"In the files below, the asserted version contain is-a and role relations as stated by the editors of the NCIt (except in the case of the tab-delimited file where role relations are excluded). The inferred version is the result of classification, and contains inferred is-a and role relations, as well as the asserted relations. In addition, annotations meant to support NCIt editors, e.g. editor notes, are excluded from all files.

**Thesaurus_16.02d.OWL.zip in OWL format (asserted version).** This file contains the entire terminology expressed in OWL. The rdf:about (rdf:ID) utilizes semantically meaningless identifiers, e.g. "C123456", which is also the value of the "code" property. The rdf:about of annotation and object properties are also replaced with their corresponding codes. This is the version of the NCIt that after classification (to generate an inferred version) is loaded into the LexEVS terminology server to support API and web browser access.

**ThesaurusInf_16.02d.OWL.zip in OWL format (inferred version).** This file is created for import into the UMLS and NCI Metathesaurus and excludes retired concepts. It uses semantically meaningless rdf:about identifiers as described above for the "asserted version".

**Comment by jamesaoverton** [comment]
I don't know what action to take on this.

**Comment by cmungall** [comment]
I think Thesaurus_16.02d.OWL.zip is the one to use, but it would be useful to know if we need to reason ourselves, and if so, what profile (ie Elk vs DL reasoner)

**Comment by jamesaoverton** [comment]
We're using Thesaurus_16.02d.OWL.zip. HermiT runs in under a minute, and it seems to add about 20,000 new subClassOf axioms. So I guess reasoning is required, and I'll add it to the Makefile.
