### ISSUE TITLE
OBO IDs should be prefixed

### ISSUE THREAD

**Issue by cmungall** [ontodev/ncit-obo#16]
```
[Term]
id: C100051
name: Renal Cell Carcinoma Associated with Neuroblastoma
def: "Renal cell carcinoma that develops in patients who are long-term survivors of childhood neuroblastoma." [] {http://purl.obolibrary.org/obo/IAO_0000119="NCI"}
synonym: "Renal Cell Carcinoma Associated with Neuroblastoma" EXACT [] {http://purl.obolibrary.org/obo/IAO_0000117="NCI"}
is_a: C9385 ! Renal Cell Carcinoma
```

Unfortunately it's a limitation of OBO and the owl2obo.

Rather than fix this in the owlapi, we can do a hacky fix as part of the pipeline, e.g. `perl -npe 's@http://ncicb.nci.nih.gov/xml/owl/EVS/Thesaurus.owl#@http://purl.obolibrary.org/obo/NCIT_@g'`

**Comment by jamesaoverton** [comment]
@cmungall implemented this in f6ecd4d405d13da1d79f5c53b603d823f72e49cb. It's still a hack, but I'll close this issue.
