### ISSUE TITLE
RTR: 'Unemployment' should not be a subclass of 'Employment'

### ISSUE THREAD

**Issue by dillerm** [ontodev/ncit-obo#21]
'Unemployment' (NCIT:C75563) is defined as "The state of not having a job."

'Employment' (NCIT:C25172) is defined as "The state of being engaged in an activity or service for wages or salary; the occupation for which you are paid."

This is contradictory. I would recommend making 'Unemployment' a sibling of 'Employment'.

**Comment by jamesaoverton** [comment]
Sorry, this repo is obsolete and not maintained. I realize that it wasn't clear, so I just updated the README to reflect that. Please refer to <https://github.com/NCI-Thesaurus/thesaurus-obo-edition> instead.

Also note that this repo and that one are for automated translations of NCIT into OBO-compatible OWL. To the best of my knowledge, a change in content like the one you're proposing would have to be made in NCIT proper.

**Comment by dillerm** [comment]
I submitted the issue through the NCIT website since it seems like the NCIT OBO folks wouldn't be able to make the requested fix. Thanks for the heads up!
