### ISSUE TITLE
Add match scoring based on synonym scopes

### ISSUE THREAD

**Issue by cmungall** [ontodev/ncit-obo#3]
in the OBO synonym model, scopes are one of `{E,B,N,R}`

The rdfs:label can be counted as `E`

Ultimately the scoring may be configurable, but for now we can hardcode some rules. The goal is to produce probabilities for 4 possibilities for any matching class pair `X,Y`:
- `X EquivalentTo Y`
- `X SubClassOf Y`
- `Y SubClassOf X`
- None of the above

I will create a table for all 16 combinations of scopes once I work out if it's possible to add tables to tickets...

**Comment by cmungall** [comment]
First pass:

```
E E => 100
E _ => 50
_ E => 50
_ _ => 25
```

**Comment by jamesaoverton** [comment]
I did a number of experiments on this back in March. I tried several string distance measures, but in the end the only good results were coming when the normalized strings are identical. I'm going to remove the distance code from `align.clj`, then I'll try to implement the "First pass" idea in the previous comment.

**Comment by jamesaoverton** [comment]
I implemented the "First pass" behaviour. Here's a TSV file with new results:
[cellular_process.txt](https://github.com/ontodev/ncit-obo/files/662166/cellular_process.txt)
