### ISSUE TITLE
hosting the NCIt obo file

### ISSUE THREAD

**Issue by cmungall** [ontodev/ncit-obo#7]
We need a place to host the NCIt obo file, so it can be easily accessed. It would probably be easiest to use this repo. We might want to move some of the more GO-specific stuff to a different repo.

Alternatively it should go in an org like obophenotype

(we should also discuss the obo registry entry for NCIt which is grandfathered in, but that is an obo ticket)

**Comment by cmungall** [comment]
@mellybelly prefers obophenotype

**Comment by cmungall** [comment]
It may be simpler to use the same github repo and arrange the different subsets in a standard way, e.g:

```
ncit.obo
ncit.owl
ncit/
   subsets/
      biological_process.{obo,owl}
      neoplasm.{obo,owl}
```

TBD whether these would be checked into github, or if they would be built in jenkins.

Also, if we check into github, do we keep the code repo separate

Looks like we would likely not check the whole OWL into GitHub, as this would require LFS

**Comment by jamesaoverton** [comment]
The OWL is now hosted at https://build.berkeleybop.org/job/ncit-obo/lastSuccessfulBuild/artifact/build/ncit.owl

I added a link to the latest ncit.owl file in the README 69e02c2605c382e974c88baad917233dfb97659a
