### ISSUE TITLE
Set up a jenkins job to run basic NCIt->OBO procedure

### ISSUE THREAD

**Issue by cmungall** [ontodev/ncit-obo#9]
See #7 for what the products should be produced. At first just the obo and owl files, but later subsets.

Note at this stage this is just for the OBO-ified NCIt; mappings etc can come later.

After this is done we can configure the ncit.md entry in OBOFoundry.github.io to have a build tag that will slurp from the job and deploy on berkeleybop.org/ontologies/ (but we would hold off on having a purl for this)

@jamesaoverton - does NCIt-obo required java8? We are not set up to do this yet, although we may have a test machine it can be pinned to, @kltm and @hdietze can advise.

But if this is at all problematic, @jnguyenx can get you set up on http://ci.monarchinitiative.org instead (assuming artefacts are public-readable?)

**Comment by jamesaoverton** [comment]
Java 7 should work fine.

I have a Jenkins account on http://build.berkeleybop.org but I think I'll need someone else to create the new job and grant me permissions.

**Comment by hdietze** [comment]
We have updated the Jenkins permissions @jamesaoverton can now create new jobs.

**Comment by jamesaoverton** [comment]
I set up a new Jenkins job here: https://build.berkeleybop.org/job/ncit-obo/

I ran into two problems:
1. The Clojure build tool `lein` ([Leiningen](http://leiningen.org)) is not installed on the build machine "satin". I added a task to the Makefile to install it, and that works fine, but it feels like a hack. Would it be better to install `lein` through the package manager?
2. Build 5 made it all the way to the last task before failing: zipping the generated OWL file. For some reason `unzip` is installed but `zip` is not? I'll remove this step for now.

**Comment by jamesaoverton** [comment]
The build results are archived, starting with build 8. The latest successful build is at https://build.berkeleybop.org/job/ncit-obo/lastSuccessfulBuild/artifact/build/

We don't have to keep the archived versions forever, just the last few, I think. But I couldn't see how to configure the number of artifacts.

@cmungall: Can we close this issue, or is there more to do?

**Comment by cmungall** [comment]
cc @kltm about `lein`

**Comment by kltm** [comment]
Hm. It's bad policy to install software this way, especially since I've found a PPA that seems to have an acceptable version of leiningen (the one in the current repo is ancient).

All of our worker machines try and have the same package profile, so unless this needs to be pinned to satin for a particular reason, we should add leiningen and zip/unzip to the slave profile.

**Comment by kltm** [comment]
@cmungall I have no power to open/close here, so could you reopen until this is resolved?

**Comment by kltm** [comment]
As well, the job should be using the label "remote" to make sure it does not leak onto a odd or protected machine.
Almost done the jenkins updates.

**Comment by kltm** [comment]
I've changed the job to be pinned to satin or smaug, which should now have the correct environment: leiningen at 2.6+, zip, and unzip.

You can go ahead and remove the manual software install.
